# -*- coding: utf-8 -*-
"""Uas_Data_sicience_TS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qB_1UsiS3Ml1Rp-mCYmMZqevzXUbigbV
"""

import pandas as pd
import numpy as np
import seaborn as sns #menghitung numerik
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import HuberRegressor, LinearRegression
from sklearn.model_selection import train_test_split
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from statsmodels.tsa.stattools import adfuller
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Load dataset
file_path = "Income Inequality in South Africa_Dataset.xlsx"
df = pd.read_excel(file_path)

"""#CEK DATA PER KOLOM

"""

print(df.head())

"""#type data"""

print(df.info())

"""#MELIHAT BARIS DAN KOLOM"""

print("Shape:", df.shape)

print(df.describe())

"""#missing value"""

print(df.isnull().sum())

# Sort berdasarkan tahun (wajib biar interpolasinya benar)
df = df.sort_values(by='Year')

# Ambil hanya kolom numerik
numeric_cols = df.select_dtypes(include='number').columns
numeric_cols = [col for col in numeric_cols if col.lower() != 'year']

# Interpolasi time series
for col in numeric_cols:
    df[col] = df[col].interpolate(method='linear')

# Simpan data sebelum interpolasi
df_original = df.copy()

# Sort berdasarkan Year
df = df.sort_values(by='Year')

# Ambil kolom numerik selain Year
numeric_cols = df.select_dtypes(include='number').columns
numeric_cols = [col for col in numeric_cols if col.lower() != "year"]

# Lakukan interpolasi
for col in numeric_cols:
    df[col] = df[col].interpolate(method='linear')

# Plot sebelum vs sesudah untuk tiap kolom
for col in numeric_cols:
    plt.figure(figsize=(10, 5))

    # before interpolation (missing values)
    plt.plot(df_original['Year'], df_original[col],
             'o', color='red', label='Before (raw)', alpha=0.7)

    # after interpolation
    plt.plot(df['Year'], df[col],
             '-', color='blue', linewidth=2, label='After Interpolation')

    plt.title(f"Interpolasi Waktu: {col}", fontsize=14, fontweight='bold')
    plt.xlabel("Year")
    plt.ylabel(col)
    plt.grid(alpha=0.3)
    plt.legend()
    plt.tight_layout()
    plt.show()

print(df.isnull().sum())

"""#FILTERING KOLOM YANG DIGUNAKAN"""

selected_cols = [
    'Year',
    'gini_disp',
    'gini_mkt',
    'Inflation rate',
    'GDP',
    'GOVEDU',
    'GOVEXP',
    'FINDEV 1',
    'DEMOCRACY',
    'FLABOUR'
]

df_filtered = df[selected_cols]

df_filtered.head()

"""#TES TIME SERIES"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Memuat dataset
file_path = 'Income Inequality in South Africa_Dataset.xlsx'
df = pd.read_excel(file_path)

# Pilih kolom yang relevan untuk analisis time series
df_gini_disp = df[['Year', 'gini_disp']].set_index('Year')

# Tampilkan beberapa data pertama untuk melihat struktur
df_gini_disp.head()

# Visualisasikan time series
df_gini_disp['gini_disp'].plot(figsize=(10, 6))
plt.title('Time Series of Gini Dispersion')
plt.xlabel('Year')
plt.ylabel('Gini Dispersion')
plt.grid(True)
plt.show()

# Statistik deskriptif untuk kolom 'gini_disp'
df_gini_disp['gini_disp'].describe()

from statsmodels.tsa.stattools import adfuller

# Uji ADF pada data 'gini_disp'
adf_result = adfuller(df_gini_disp['gini_disp'].dropna())

# Ekstrak hasil statistik ADF dan p-value
adf_statistic = adf_result[0]
adf_p_value = adf_result[1]

print(f'ADF Statistic: {adf_statistic}')
print(f'p-value: {adf_p_value}')

# Apply first differencing
df_gini_disp_diff = df_gini_disp['gini_disp'].diff().dropna()

# Uji ADF lagi setelah differencing pertama
adf_result_diff = adfuller(df_gini_disp_diff)

# Hasil uji ADF setelah differencing
adf_statistic_diff = adf_result_diff[0]
adf_p_value_diff = adf_result_diff[1]

print(f'ADF Statistic (After Differencing): {adf_statistic_diff}')
print(f'p-value (After Differencing): {adf_p_value_diff}')

# Apply second differencing to the data
df_gini_disp_diff2 = df_gini_disp_diff.diff().dropna()

# Perform the ADF test again on the second differenced data
adf_result_diff2 = adfuller(df_gini_disp_diff2)

# Extract the test statistic and p-value for second differenced data
adf_statistic_diff2 = adf_result_diff2[0]
adf_p_value_diff2 = adf_result_diff2[1]

adf_statistic_diff2, adf_p_value_diff2

df_gini_disp['gini_disp'] = df_gini_disp['gini_disp'].interpolate(method='linear')

# Mengisi missing values dengan interpolasi linear
df_gini_disp['gini_disp'] = df_gini_disp['gini_disp'].interpolate(method='linear')

# Dekomposisi time series (memisahkan tren, musiman, dan residual)
from statsmodels.tsa.seasonal import seasonal_decompose

decomposition = seasonal_decompose(df_gini_disp['gini_disp'], model='additive', period=1)

# Tampilkan hasil dekomposisi
decomposition.plot()
plt.show()

from statsmodels.tsa.seasonal import seasonal_decompose

# Dekomposisi time series (memisahkan tren, musiman, dan residual)
decomposition = seasonal_decompose(df_gini_disp['gini_disp'], model='additive', period=1)

# Tampilkan hasil dekomposisi
decomposition.plot()
plt.show()

# Menyimpan output untuk tren, musiman, dan residual
trend = decomposition.trend
seasonal = decomposition.seasonal
residual = decomposition.resid

# Menampilkan hasil
print("Tren:")
print(trend.tail())

print("\nMusiman:")
print(seasonal.tail())

print("\nResidual:")
print(residual.tail())

from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

# Plot ACF dan PACF untuk data yang telah di-differencing kedua
fig, ax = plt.subplots(1, 2, figsize=(15, 5))

# ACF plot
plot_acf(df_gini_disp_diff2, lags=20, ax=ax[0])
ax[0].set_title('Autocorrelation Function (ACF)')

# PACF plot
plot_pacf(df_gini_disp_diff2, lags=20, ax=ax[1])
ax[1].set_title('Partial Autocorrelation Function (PACF)')

plt.show()

from statsmodels.tsa.stattools import adfuller

# Gantikan nilai tak terhingga (infiniti) dengan NaN dan hapus NaN
series = df["gini_disp"].replace([np.inf, -np.inf], np.nan).dropna()

# Lakukan uji Augmented Dickey-Fuller (ADF)
result = adfuller(series)

# Tampilkan hasil uji ADF
print("ADF Statistic :", result[0])
print("p-value       :", result[1])
print("Critical Value:")
for k, v in result[4].items():
    print(f"   {k} : {v}")

from statsmodels.tsa.stattools import acf, pacf

# Menghitung ACF dan PACF untuk data yang telah di-differencing kedua
acf_values = acf(df_gini_disp_diff2, nlags=20)
pacf_values = pacf(df_gini_disp_diff2, nlags=20)

# Menampilkan hasil ACF
print("ACF (Autocorrelation Function) Values:")
for i, value in enumerate(acf_values):
    print(f"Lag {i}: {value}")

# Menampilkan hasil PACF
print("\nPACF (Partial Autocorrelation Function) Values:")
for i, value in enumerate(pacf_values):
    print(f"Lag {i}: {value}")

"""# BOXPLOT (Out Layer)"""

# Pilih kolom numerik kecuali 'Year'
numeric_cols = df.select_dtypes(include='number').columns
numeric_cols = [col for col in numeric_cols if col.lower() != "year"]

# Loop kolom dan buat boxplot satu-satu
for col in numeric_cols:
    plt.figure(figsize=(10, 7))
    plt.boxplot(df[col].dropna())
    plt.title(f"Boxplot {col}")
    plt.ylabel(col)
    plt.xticks([1], [col])
    plt.grid(True)
    plt.show()

"""#MODELING DES

##Persiapan Data
"""

import numpy as np
import matplotlib.pyplot as plt

# --- ambil data GINI_Disp ---
df_fc = df_filtered[["Year", "gini_disp"]].dropna()
df_fc = df_fc.sort_values("Year")

tahun = df_fc["Year"].values
y = df_fc["gini_disp"].values

# parameter smoothing (Brown → hanya alpha)
alpha = 0.1

S1 = [y[0]]
S2 = [y[0]]

# double exponential smoothing (Brown)
for t in range(1, len(y)):
    S1.append(alpha * y[t] + (1 - alpha) * S1[t-1])
    S2.append(alpha * S1[t] + (1 - alpha) * S2[t-1])   # <- diperbaiki

# komponen a & b (Brown)
a = [2*S1[i] - S2[i] for i in range(len(y))]
b = [(alpha/(1-alpha)) * (S1[i] - S2[i]) for i in range(len(y))]

# forecast in-sample
forecast = [np.nan]
for i in range(1, len(y)):
    forecast.append(a[i-1] + b[i-1])

# error
error = [np.nan]
abs_error = [np.nan]
error2 = [np.nan]

for i in range(1, len(y)):
    e = y[i] - forecast[i]
    error.append(e)
    abs_error.append(abs(e))
    error2.append(e**2)

# MAPE
valid_error = np.array(abs_error[1:]) / np.array(y[1:])
mape = np.nanmean(valid_error) * 100

# hasil tabel
tabel = pd.DataFrame({
    'Year': tahun,
    'gini_disp': y,
    "S1": S1,
    "S2": S2,
    'a': a,
    'b': b,
    'Forecast': forecast,
    'Error': error,
    'Abs Error': abs_error,
    'Error²': error2
})

print("\n=== Tabel Detail Perhitungan Double Exponential Smoothing ===")
print("")
print(tabel)
print(f"\nMAPE: {mape:.2f}%")
print("\n=== MAPE ===")
print(f"{mape:.2f}%")

# forecasting 5 tahun ke depan
future_years = np.arange(tahun[-1] + 1, tahun[-1] + 6)
future_forecast = [a[-1] + b[-1]*m for m in range(1, 6)]

hasil_forecast = pd.DataFrame({
    'Year': list(tahun) + list(future_years),
    'Forecast_GINI_Disp': list(forecast) + list(future_forecast)
})

print("\n=== Forecast 5 Tahun ke Depan ===")
print(hasil_forecast.tail(5))

# visualisasi
plt.figure(figsize=(10,5))
plt.plot(tahun, y, marker='o', label='Actual GINI_Disp')
plt.plot(hasil_forecast['Year'], hasil_forecast['Forecast_GINI_Disp'],
         marker='x', linestyle='--', label='Forecast GINI_Disp')

plt.title('Forecasting GINI Dispersion (Double Exponential Smoothing)')
plt.xlabel('Year')
plt.ylabel('GINI Disp')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

actual_eval = y[1:]
forecast_eval = np.array(forecast[1:])

# Hitung MSE, RMSE, MAE, MAPE
mse = mean_squared_error(actual_eval, forecast_eval)
rmse = np.sqrt(mse)
mae = mean_absolute_error(actual_eval, forecast_eval)
mape_final = np.mean(np.abs((actual_eval - forecast_eval) / actual_eval)) * 100

print("\n=== Evaluasi Model DES ===")
print(f"MSE  : {mse:.4f}")
print(f"RMSE : {rmse:.4f}")
print(f"MAE  : {mae:.4f}")
print(f"MAPE : {mape_final:.2f}%")